table Parameter
	lineageTag: ac5abe95-4bbb-4fea-9203-7db6658a7c05

	measure 'Parameter Value' = SELECTEDVALUE('Parameter'[Parameter])
		formatString: 0
		lineageTag: c75ff83c-35fd-41ad-a512-c977275fa610

	column Parameter
		dataType: int64
		formatString: 0
		lineageTag: a77f9a2b-00f4-460b-9425-2e8826897b4a
		summarizeBy: none
		isDataTypeInferred
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition Parameter-ba15b8e5-991c-40ab-b53d-08b34ee43690 = calculated
		mode: import
		source = {2009,2010,2011,2012,2013,2014,2015,2016,2019,2022}

	annotation PBI_Id = ce98325e9e494a73abeb9444d217ea3b

